{% set name = "detect-test-pollution" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/detect_test_pollution-{{ version }}.tar.gz
  sha256: 94f383759bbab309771ceedb8dd526a62fa59607e5f7e41f5b33bbc656bfcea9

build:
  entry_points:
    - detect-test-pollution = detect_test_pollution:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - detect_test_pollution
  commands:
    - pip check
    - detect-test-pollution --help
  requires:
    - pip
    - pytest

about:
  home: https://github.com/asottile/detect-test-pollution
  summary: a tool to detect test pollution
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
